version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./backend/admin/:/var/www/backend/admin
      - ./backend/api/:/var/www/backend/api
      - ./frontend/:/app
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - admin
      - api
      - frontend
    container_name: some_rofls_nginx

  admin:
    build:
      context: ./backend/admin
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - ./backend/admin/:/var/www/backend/admin
    depends_on:
      - db
    container_name: some_rofls_admin

  api:
    build:
      context: ./backend/api
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - ./backend/api/:/var/www/backend/api
    depends_on:
      - db
    container_name: some_rofls_api

  frontend:
    build:
      context: ./frontend
      dockerfile: ./_docker/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/:/app
    container_name: some_rofls_frontend

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: some_rofls_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: some_rofls_db